# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia_implementations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oppiaimplementation',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oppiaimplementation',
            name='oppia_code_version',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oppiaimplementation',
            name='server_admin_email',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
