# Generated by Django 2.1.5 on 2019-02-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia_implementations', '0003_auto_20180419_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oppiaimplementation',
            name='implementation_logo',
            field=models.FileField(blank=True, default=None, upload_to='implementation_logo'),
        ),
        migrations.AlterField(
            model_name='oppiaimplementation',
            name='organisation_logo',
            field=models.FileField(blank=True, default=None, upload_to='organisation_logo'),
        ),
    ]
