# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia_implementations', '0003_auto_20180419_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementationdatakv',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
