# Generated by Django 2.1.5 on 2019-02-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oppia_implementations', '0004_auto_20190212_2013'),
        ('oppia_implementations', '0004_implementationdatakv_is_visible'),
    ]

    operations = [
    ]
