# Generated by Django 2.2.24 on 2021-06-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia_implementations', '0006_auto_20210524_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementationdatakv',
            name='value_bool',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
