# Generated by Django 2.2.24 on 2021-06-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia_implementations', '0008_auto_20210622_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementationdatakv',
            name='value_bool',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
